apiVersion: apps/v1
kind: Deployment
metadata:
  name: amoeba-go-deployment
  namespace: amoeba-go
  labels:
    app: amoeba-go-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amoeba-go
  template:
    metadata:
      labels:
        app: amoeba-go
    spec:
      containers:
      - name: amoeba-go
        image: asia-east1-docker.pkg.dev/devops-349314/amamoeba-docker/amoeba-backend-go:v2.1
        workingDir: /opt/go
        # command: ["/bin/sh", "-c", "/opt/go/amoeba_backend"," api"]
        command: ["/bin/sh", "-c", "./amoeba_backend api"]
        ports:
        - containerPort: 80
          name: amoeba-go-port
        env:
          - name: db_host
            value: amoeba-db-service
          - name: redis_host
            value: amoeba-redis-service
          - name: db_port
            valueFrom:
              configMapKeyRef:
                name: amoeba-backend-config
                key: db_port
          - name: db_name
            valueFrom:
              configMapKeyRef:
                name: amoeba-backend-config
                key: db_name
          - name: redis_port
            valueFrom:
              configMapKeyRef:
                name: amoeba-backend-config
                key: redis_port
          - name: redis_db
            valueFrom:
              configMapKeyRef:
                name: amoeba-backend-config
                key: redis_db
          - name: jwt_token_time
            valueFrom:
              configMapKeyRef:
                name: amoeba-backend-config
                key: jwt_token_time
          - name: jwt_ref_token_time
            valueFrom:
              configMapKeyRef:
                name: amoeba-backend-config
                key: jwt_ref_token_time
          - name: web_gin
            valueFrom:
              configMapKeyRef:
                name: amoeba-backend-config
                key: web_gin
          - name: swagger_port
            valueFrom:
              configMapKeyRef:
                name: amoeba-backend-config
                key: swagger_port
          - name: db_username
            valueFrom:
              secretKeyRef:
                name: amoeba-backend-secret
                key: db_username
                optional: false
          - name: db_password
            valueFrom:
              secretKeyRef:
                name: amoeba-backend-secret
                key: db_password
                optional: false
          - name: redis_password
            valueFrom:
              secretKeyRef:
                name: amoeba-backend-secret
                key: redis_password
                optional: false
          - name: jwt_secret
            valueFrom:
              secretKeyRef:
                name: amoeba-backend-secret
                key: jwt_secret
                optional: false