apiVersion: v1
kind: ConfigMap
metadata:
  name: amoeba-go-config
data:
  # property-like keys; each key maps to a simple value
  #db setting
  db_host: "172.21.0.2"
  db_port: "3306"
  db_name: "amoeba"

  #redis setting
  redis_host: "172.21.0.3"
  redis_port: "6379"
  redis_db: "0"

  #web setting
  web_host: "amoeba.com" 
  web_port: ""
  jwt_token_time: "480"
  jwt_ref_token_time: "1440"

  #gin setting
  web_gin: "release"

  #swagger port
  swagger_port: "8888"