apiVersion: v1
kind: ConfigMap
metadata:
  name: amoeba-backend-config
  namespace: amoeba-go
data:
  # property-like keys; each key maps to a simple value

  #web setting
  web_host: "amoeba.com" 
  web_port: "80"
  jwt_token_time: "480"
  jwt_ref_token_time: "1440"

  #gin setting (release/debug)
  web_gin: "debug"

  #swagger port
  swagger_port: "80"

  #redis setting
  redis_port: "6379"
  redis_db: "0"

  #redis config volume
  redis_config: |
    bind 0.0.0.0

  #db setting
  db_port: "3306"
  db_name: "amoeba"
  privileged: "true"

  #db sql volume
  db_sql: |
    GRANT INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,SELECT,ALTER,SHOW DATABASES,CREATE TEMPORARY TABLES,LOCK TABLES,EXECUTE,CREATE VIEW,SHOW VIEW,CREATE ROUTINE,ALTER ROUTINE,CREATE USER,EVENT,TRIGGER,CREATE TABLESPACE,CREATE ROLE ON *.* TO 'amoeba'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
  
  #db config volume
  db_config: |
    [mysqld]
    back_log = 3000
    character_set_server = utf8mb4
    collation_server = utf8mb4_general_ci
    max_connect_errors = 100
    max_connections = 16050
    max_user_connections = 16050
    max_heap_table_size = 64M
    max_allowed_packet = 1024M
    sort_buffer_size = 848KB
    read_buffer_size = 848KB
    read_rnd_buffer_size = 432KB
    join_buffer_size = 432KB
    net_buffer_length = 16K
    transaction_isolation = READ-COMMITTED
    lower_case_table_names = 1
    auto_increment_increment = 1
    auto_increment_offset = 1
    bulk_insert_buffer_size = 4M
    innodb_buffer_pool_size = 2048M
    innodb_log_file_size = 256M
    innodb_flush_method = O_DIRECT
    default-time-zone = '+08:00'
    skip-name-resolve
    wait_timeout=600
    log_output=file
    slow_query_log=ON
    slow_query_log_file=/var/lib/mysql/sqls-slow.log
    log_queries_not_using_indexes=OFF
    long_query_time=3