apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amoeba-backend-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: amoeba-go-service
            port:
              number: 80
  - https:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: amoeba-go-service
            port:
              number: 80